### ISSUE TITLE
[ContentBundle] template change: copy data into new fields

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#440] opened 2014-11-04 13:43 UTC
<a href="https://github.com/turbo-ele"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/5152633?v=2" /></a>
By @turbo-ele *from* https://github.com/sulu-cmf/SuluContentBundle/issues/92

an extra attribute should define if content is shareable between templates.

**Comment by danrot** [comment] 2015-02-14 08:36
Duplicate of #46

**Closed by danrot** 2015-02-14 08:36 UTC
Labels: Enhancement, medium
