### ISSUE TITLE
[MediaBundle] Bugs after Uploading a new file version

### ISSUE THREAD

**Issue by sulu-io** [sulu-cmf/sulu#448] opened 2014-11-04 13:43 UTC
<a href="https://github.com/pjeroen"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/513131?v=2" /></a>
By @pjeroen *from* https://github.com/sulu-cmf/SuluMediaBundle/issues/72

- After uploading a new file version, the previous contents for title, description and tags are deleted.
- After confirming, the listview has to be updated, in order to show the new file thumbnail.

**Comment by danrot** [comment] 2015-02-14 08:27
Your first bug seems to be fixed, the other one is a duplicate of #770

**Closed by danrot** 2015-02-14 08:27 UTC
Labels: Bug, duplicate, medium
