### ISSUE TITLE
Page save show error 500 after update to 0.14.0

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu#712] opened 2015-01-14 10:13 UTC
Log:
```
 POST http://sulu.lo/admin/content/preview/909a646d-47a5-4058-938b-116c7e63f147/update?webspace=default&language=de
500 (Internal Server Error)
husky.js:10763
sendhusky.js:10193
jQuery.extend.ajaxmain.js:34
ajax.updatemain.js:240
updatemain.js:268
updateEventhusky.js:7152
jQuery.event.dispatchhusky.js:6823
elemData.handlehusky.js:7064
jQuery.event.triggerhusky.js:7387
jQuery.event.simulatehusky.js:7638 handler
```

But Preview seems to work correctly.

**Comment by danrot** [comment] 2015-01-14 10:19
Can you add a bit more information? Which fields have you been editing? Are you running on the websocket?

**Comment by wachterjohannes** [comment] 2015-02-04 15:33
@alexander-schranz ping (=

**Comment by danrot** [comment] 2015-02-05 09:21
I'll close it, since the preview has changed a lot. @alexander-schranz Please reopen if the problem is still existing.

**Closed by danrot** 2015-02-05 09:21 UTC
Labels: Bug

**Comment by alexander-schranz** [comment] 2015-02-05 09:24
ok will test the new preview as soon as possible
